### ISSUE TITLE
Crash while starting Minecraft

### ISSUE THREAD

**Issue by davidbourg1981** [joshiejack/Enchiridion#101]
The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Duplicate enchantment id! class mrcomputerghost.runicdungeons.ench.EnchantmentPoisonThorns and class mariculture.magic.enchantments.EnchantmentRestore Enchantment ID:84

**Comment by GirafiStudios** [comment]
This is a Mariculture/Runic Dungeons related issue. Have nothing to do with Enchiridion.
