### ISSUE TITLE
[1.12.1] crash with guideAPI

### ISSUE THREAD

**Issue by jonqrandom** [joshiejack/Enchiridion#102]
forge 14.22.1.2485, latest versions of both mods, reproduced with only the two mods installed;

main log: https://hastebin.com/ozeqafusah.tex

crash log: https://hastebin.com/fehusazira.sql

sorry! u.u';

should i make an issue/reference this in guideAPI's tracker too?

**Comment by GirafiStudios** [comment]
Thanks for the report!
I will look into fixing is as soon as possible!

**Comment by jonqrandom** [comment]
that was amazingly fast, thank you! :D

**Comment by GirafiStudios** [comment]
No problem! It was a quick fix, just overlooked it in the last build.
