### ISSUE TITLE
Suggestion - Single Page Note Option

### ISSUE THREAD

**Issue by Boolyman** [joshiejack/Enchiridion#103]
I was hoping to offer a suggestion that I think would be very helpful for modpack makers, and also stick to the theme of your mod.  In addition to having a full book, it would be very helpful if there was an option to just create a single page "flyer" or note.  Some times I want to give the player a custom schematic or diagram, and don't really need an entire book to do it.  I can create a 1-page book, but it looks kind of silly to do that.

**Comment by Sketaful** [comment]
Just use a full paper background instead of a book background. Works for me.
