### ISSUE TITLE
Clicking on recipe or item in book editor crashes game

### ISSUE THREAD

**Issue by dragon3025** [joshiejack/Enchiridion#104]
Minecraft: 1.12.1
Forge: 1.12.1-forge1.12.1-14.22.1.2478
Mod Version: Enchiridion-1.12.2-3.3.1.jar

When clicking on recipe or item in book editor it crashes, here's the crash report: https://pastebin.com/499HRWdG

**Comment by GirafiStudios** [comment]
Thanks for your report!
Will be fixed in the next version of Enchiridion. Should be out later.
