### ISSUE TITLE
Works terribly in 1.12.x

### ISSUE THREAD

**Issue by NovaViper** [joshiejack/Enchiridion#105]
The mod barely works in all 1.12 versions. When I make a new book, it only shows one character and whenever I get new books, they have that purple and black missing texture. Also, whenever I open the "Getting Started" book, it just shows a dot and nothing else. I just got a crash aswell:

[fml-client-latest.log](https://github.com/PenguinSquad/Enchiridion/files/1385751/fml-client-latest.log)

**Comment by GirafiStudios** [comment]
This is properly because you are using Sponge. Try with just plain forge.

**Comment by NovaViper** [comment]
I'm not using Sponge, just normal Forge

**Comment by GirafiStudios** [comment]
Just saw that org.spongepowered was mentioned in the log.
It's clearly some other mods ASM that is causing this problem. Try without Optifine. If it doesn't work without Optifine then try without TTFR

**Comment by NovaViper** [comment]
I took out every mod except Guidebook, and it's still too small

**Comment by NovaViper** [comment]
There is something I noticed though, when I have the game not maximized (with both mods and no mods), it scales correctly

**Comment by GirafiStudios** [comment]
You never mentioned anything about  anything being too small before now?
The scaling can be a bit wonky, that is a known issue, if that is all this is.

**Comment by NovaViper** [comment]
I just started using this mod today and I saw that the scaling was really small with the large gui scaling

**Comment by NovaViper** [comment]
And I did mention something being too small: the gui itself when the book opens is too small

**Comment by NovaViper** [comment]
Oh shoot! This is the completely wrong issue! I accidentally posted my issue about the scaling on this issue instead of another one I was having before. Sorry for the confusion!

**Comment by GirafiStudios** [comment]
In that case I'm closing this.
It depends on your GUI scale and monitor size.

**Comment by NovaViper** [comment]
I thought this was the [Guidebook issue ](https://github.com/gigaherz/Guidebook/issues/29)I made moments earlier. I also just realized that I put the Guidebook mod to test that out instead of the Enchiridion mod. Sorry about that confusion

**Comment by NovaViper** [comment]
Huh, the mod seems to function as normal when I take out all of the various mods I have. I'm going to test and see if its the LiteLoader mod, which loads VoxelMap

**Comment by NovaViper** [comment]
O_o... Uh, I thought it was LiteLoader, but apparently now the game decided to fix itself as I put LiteLoader in and it all works now
