### ISSUE TITLE
All of my enchiridion books have taken on the texture of the Spellforger's Codex (from Wizardry)

### ISSUE THREAD

**Issue by belathus** [joshiejack/Enchiridion#108]
All of the books normally have their own texture. Pulling Wizardry causes the books to have their own texture again.

This mod: https://minecraft.curseforge.com/projects/wizardry-mod?gameCategorySlug=mc-mods&projectID=278155

**Comment by GirafiStudios** [comment]
Thanks for your report!
As Demoniaque said in https://github.com/TeamWizardry/Wizardry/issues/129, it's most likely caused by Wizardry Mod Mod.
