### ISSUE TITLE
Text display error

### ISSUE THREAD

**Issue by Mrkwtkr** [joshiejack/Enchiridion#11]
Chinese characters become black rectangles in the diving suit pages. This cannot be fixed by changing their size.
Comparison
All in chinese:http://puu.sh/aQXZJ/a77246e17a.jpg
All in english:http://puu.sh/aR361/da91457621.jpg
Left in chinese(changed size and wrap value) while right in english:http://puu.sh/aR350/c8c27ada25.jpg
It will be very helpful if u can tell me whats wrong with that.

**Comment by joshiejack** [comment]
I think I will close this. Since no point in it remaining open with Enchiridion 2 underway.

**Comment by GustoniaEagle** [comment]
This needs to be re-opened. Issue still persists with Enchiridion 2 apparently. See: http://minecraft.curseforge.com/mc-mods/222637-adventurers-amulets#c17

**Comment by Joccob** [comment]
Its true, Enchiridion 2 still have this problem. Hope you can fix it ~
