### ISSUE TITLE
Problems when using § symbol to format text in text editor.

### ISSUE THREAD

**Issue by TeetoKaziim** [joshiejack/Enchiridion#111]
Initially when editing a book, it looks fine, but upon reloading the game, garbage unicode characters are appended on to the text fields. Subsequent reloads result in more being added. Looking at the book json, the characters are being added there too, it's not just an ingame display thing.

https://i.imgur.com/Njg4UWn.png

**Comment by GirafiStudios** [comment]
Thank you for you report!
After digging around and trying to figure out the issue for a bit, I was not able to reproduce it.
https://i.imgur.com/kC10YKm.png
