### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by thanasishadow** [joshiejack/Enchiridion#114]
Minecraft 1.12.2
Forge 14.23.4.2739
Enchiridion 3.3.3 (latest)

https://s15.postimg.cc/ocluycnuj/image.png

**Comment by GirafiStudios** [comment]
Thank you for you report!
I cannot reproduce your issues. You clearly have a bunch of other mods installed, so it's most likely some other mod causing issues on our side.
If you figure out what other mod/mods that is causing it, please let me know.

**Comment by GrucciNishikino** [comment]
Not a satisfying conclusion to this issue I am also having. I am currently determining which mod is causing problems so that you can fix it.

**Comment by GrucciNishikino** [comment]
latest.log says that my book was never actually loaded. This is a problem, no?
