### ISSUE TITLE
Crash on client side on startup

### ISSUE THREAD

**Issue by tacogerbil** [joshiejack/Enchiridion#116]
Previous versions worked fine

**Comment by tacogerbil** [comment]
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 2018-12-20 17:58:56 PST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Enchiridion (enchiridion)
Caused by: java.lang.NoSuchMethodError: net.minecraftforge.fml.common.ObfuscationReflectionHelper.getPrivateValue(Ljava/lang/Class;Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
    at joshie.enchiridion.EClientProxy.onConstruction(EClientProxy.java:58)
    at joshie.enchiridion.Enchiridion.onConstruction(Enchiridion.java:41)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:466)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3930)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.13.6
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot™ 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 4479337992 bytes (4271 MB) / 6628048896 bytes (6321 MB) up to 7635730432 bytes (7282 MB)
  JVM Flags: 3 total; -Xms4096M -Xmx8192M -XX:MaxPermSize=1024M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2770 Optifine OptiFine_1.12.2_HD_U_E3 156 mods loaded, 156 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                           | Version                      | Source                                                         | Signature                                |
       |:----- |:-------------------------------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
       | UC    | minecraft                                    | 1.12.2                       | minecraft.jar                                                  | None                                     |
       | UC    | mcp                                          | 9.42                         | minecraft.jar                                                  | None                                     |
       | UC    | FML                                          | 8.0.99.99                    | forge-1.12.2-14.23.5.2770.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | forge                                        | 14.23.5.2770                 | forge-1.12.2-14.23.5.2770.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UC    | creativecoredummy                            | 1.0.0                        | minecraft.jar                                                  | None                                     |
       | UC    | com.elytradev.movingworld.common.asm.coremod |                              | minecraft.jar                                                  | None                                     |
       | UC    | openmodscore                                 | 0.12.1                       | minecraft.jar                                                  | None                                     |
       | UC    | foamfixcore                                  | 7.7.4                        | minecraft.jar                                                  | None                                     |
       | UC    | obfuscate                                    | 0.2.6                        | minecraft.jar                                                  | None                                     |
       | UC    | randompatches                                | 1.12.2-1.11.0.0              | randompatches-1.12.2-1.11.0.0.jar                              | None                                     |
       | UC    | techguns_core                                | 1.12.2-1.0                   | minecraft.jar                                                  | None                                     |
       | UC    | securitycraft                                | v1.8.10                      | [1.12.2]+SecurityCraft+v1.8.10.jar                             | None                                     |
       | UC    | bspkrscore                                   | 7.6.0.1                      | [1.12]bspkrsCore-universal-7.6.0.1.jar                         | None                                     |
       | UC    | armorstatushud                               | 1.43.0                       | [1.12]ArmorStatusHUD-client-1.43.0.jar                         | None                                     |
       | UC    | statuseffecthud                              | 1.43.0                       | [1.12]StatusEffectHUD-client-1.43.0.jar                        | None                                     |
       | UC    | actuallyadditions                            | 1.12.2-r144                  | ActuallyAdditions-1.12.2-r144.jar                              | None                                     |
       | UC    | additionalbanners                            | 1.1.43                       | AdditionalBanners-1.12.2-1.1.43.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | applecore                                    | 3.1.4                        | AppleCore-mc1.12.2-3.1.4.jar                                   | None                                     |
       | UC    | jei                                          | 4.14.3.237                   | jei_1.12.2-4.14.3.237.jar                                      | None                                     |
       | UC    | appleskin                                    | 1.0.9                        | AppleSkin-mc1.12-1.0.9.jar                                     | None                                     |
       | UC    | attributefix                                 | 1.0.4                        | AttributeFix-1.12.2-1.0.4.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | quark                                        | r1.5-135                     | Quark-r1.5-135.jar                                             | None                                     |
       | UC    | autoreglib                                   | 1.3-21                       | AutoRegLib-1.3-21.jar                                          | None                                     |
       | UC    | B3M                                          | 1.12.2-02                    | B3M-1.12.2-02.jar                                              | None                                     |
       | UC    | backpacks16840                               | 3.5.5                        | backpacks 1.12.2 - 3.5.5.jar                                   | None                                     |
       | UC    | baubles                                      | 1.5.2                        | Baubles-1.12-1.5.2.jar                                         | None                                     |
       | UC    | bibliocraft                                  | 2.4.5                        | BiblioCraft_Paintings_[v2.4.5][MC1.12.2].jar                   | None                                     |
       | UC    | bookshelf                                    | 2.3.569                      | Bookshelf-1.12.2-2.3.569.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | carryon                                      | 1.12.1                       | CarryOn+MC1.12.2+v1.12.1.jar                                   | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | UC    | champions                                    | 1.12.2-0.8-beta              | champions-1.12.2-0.8-beta.jar                                  | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UC    | chattweaks                                   | 5.1.20                       | ChatTweaks_1.12.2-5.1.20.jar                                   | None                                     |
       | UC    | ctm                                          | MC1.12.2-0.3.3.22            | CTM-MC1.12.2-0.3.3.22.jar                                      | None                                     |
       | UC    | chisel                                       | MC1.12.2-0.2.1.35            | Chisel-MC1.12.2-0.2.1.35.jar                                   | None                                     |
       | UC    | chopdownupdated                              | 1.12.2-1.2.4                 | chopdownupdated-1.12.2-1.2.4.jar                               | None                                     |
       | UC    | christmasfestivity                           | 1.2.1.5                      | ChristmasFestivityMod-1.12.2-1.2.1.5.jar                       | None                                     |
       | UC    | redstoneflux                                 | 2.1.0                        | RedstoneFlux-1.12-2.1.0.6-universal.jar                        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | cofhcore                                     | 4.6.1                        | CoFHCore-1.12.2-4.6.1.22-universal.jar                         | None                                     |
       | UC    | cofhworld                                    | 1.3.0                        | CoFHWorld-1.12.2-1.3.0.6-universal.jar                         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | cookingforblockheads                         | 6.4.65                       | CookingForBlockheads_1.12.2-6.4.65.jar                         | None                                     |
       | UC    | extendedrenderer                             | v1.0                         | coroutil-1.12.1-1.2.14.jar                                     | None                                     |
       | UC    | coroutil                                     | 1.12.1-1.2.14                | coroutil-1.12.1-1.2.14.jar                                     | None                                     |
       | UC    | configmod                                    | v1.0                         | coroutil-1.12.1-1.2.14.jar                                     | None                                     |
       | UC    | craftingtweaks                               | 8.1.9                        | CraftingTweaks_1.12.2-8.1.9.jar                                | None                                     |
       | UC    | creativecore                                 | 1.9.9                        | CreativeCore_v1.9.35_mc1.12.2.jar                              | None                                     |
       | UC    | custommainmenu                               | 2.0.9                        | CustomMainMenu-MC1.12.2-2.0.9.jar                              | None                                     |
       | UC    | dmonsters                                    | 1.7                          | Deadly+Monsters+1.71.jar                                       | None                                     |
       | UC    | dungeonmobs                                  | 5.5.1                        | dungeonmobs-5.5.1-MC1.12.2.jar                                 | None                                     |
       | UC    | eplus                                        | 5.0.174                      | EnchantingPlus-1.12.2-5.0.174.jar                              | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | endercore                                    | 1.12.2-0.5.43                | EnderCore-1.12.2-0.5.43.jar                                    | None                                     |
       | UC    | thermalfoundation                            | 2.6.1                        | ThermalFoundation-1.12.2-2.6.1.22-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | codechickenlib                               | 3.2.2.353                    | ~CodeChickenLib-1.12.2-3.2.2.353-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | thermalexpansion                             | 5.5.2                        | ThermalExpansion-1.12.2-5.5.2.39-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | enderio                                      | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderiointegrationtic                        | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderiobase                                  | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderioconduits                              | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderioconduitsappliedenergistics            | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderioconduitsopencomputers                 | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | refinedstorage                               | 1.6.12                       | refinedstorage-1.6.12.jar                                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | UC    | enderioconduitsrefinedstorage                | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderiointegrationforestry                   | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | mantle                                       | 1.12-1.3.3.39                | Mantle-1.12-1.3.3.39.jar                                       | None                                     |
       | UC    | twilightforest                               | 3.8.689                      | twilightforest-1.12.2-3.8.689-universal.jar                    | None                                     |
       | UC    | tconstruct                                   | 1.12.2-2.11.0.106            | TConstruct-1.12.2-2.11.0.106.jar                               | None                                     |
       | UC    | enderiointegrationticlate                    | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | ftblib                                       | 5.4.0.73                     | FTBLib-5.4.0.73.jar                                            | None                                     |
       | UC    | enderiomachines                              | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderiopowertools                            | 5.0.38                       | EnderIO-1.12.2-5.0.38.jar                                      | None                                     |
       | UC    | enderstorage                                 | 2.4.5.135                    | EnderStorage-1.12.2-2.4.5.135-universal.jar                    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | farmingforblockheads                         | 3.1.26                       | FarmingForBlockheads_1.12.2-3.1.26.jar                         | None                                     |
       | UC    | flatcoloredblocks                            | mc1.12-6.6                   | flatcoloredblocks-mc1.12-6.6.jar                               | None                                     |
       | UC    | foamfix                                      | 0.10.3-1.12.2                | foamfix-0.10.3-1.12.2.jar                                      | None                                     |
       | UC    | ftbutilities                                 | 5.3.0.68                     | FTBUtilities-5.3.0.68.jar                                      | None                                     |
       | UC    | funkylocomotion                              | 1.0                          | funky-locomotion-1.12.2-1.1.2.jar                              | None                                     |
       | UC    | cfm                                          | 6.2.0                        | furniture-6.2.0-1.12.2.jar                                     | None                                     |
       | UC    | ichunutil                                    | 7.1.4                        | iChunUtil-1.12.2-7.1.4.jar                                     | None                                     |
       | UC    | hats                                         | 7.0.0                        | Hats-1.12.2-7.0.2.jar                                          | None                                     |
       | UC    | hatstand                                     | 7.0.0                        | HatStand-1.12.2-7.0.1.jar                                      | None                                     |
       | UC    | heroicarmory                                 | 1.1.3                        | heroicarmory-1.2.0.jar                                         | None                                     |
       | UC    | waila                                        | 1.8.26                       | Hwyla-1.8.26-B41_1.12.2.jar                                    | None                                     |
       | UC    | inspirations                                 | 1.12.2-0.2.3                 | Inspirations-1.12.2-0.2.3.jar                                  | None                                     |
       | UC    | inventorytweaks                              | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UC    | journeymap                                   | 1.12.2-5.5.3                 | journeymap-1.12.2-5.5.3.jar                                    | None                                     |
       | UC    | kleeslabs                                    | 5.4.11                       | KleeSlabs_1.12.2-5.4.11.jar                                    | None                                     |
       | UC    | mekanism                                     | 1.12.2-9.4.13.349            | Mekanism-1.12.2-9.4.13.349.jar                                 | None                                     |
       | UC    | mekanismgenerators                           | 9.4.11                       | MekanismGenerators-1.12.2-9.4.13.349.jar                       | None                                     |
       | UC    | mekanismtools                                | 9.4.11                       | MekanismTools-1.12.2-9.4.13.349.jar                            | None                                     |
       | UC    | minemenu                                     | 1.6.4                        | MineMenu-1.12.2-1.6.4-universal.jar                            | None                                     |
       | UC    | mobamputation                                | 7.0.0                        | MobAmputation-1.12.2-7.0.0.jar                                 | None                                     |
       | UC    | mobdismemberment                             | 7.0.0                        | MobDismemberment-1.12.2-7.0.0.jar                              | None                                     |
       | UC    | guilib                                       | $version                     | morepaintings-paintings-1.12.2-5.0.0.2.jar                     | None                                     |
       | UC    | paintingselgui                               | $version                     | morepaintings-paintings-1.12.2-5.0.0.2.jar                     | None                                     |
       | UC    | morepaintings                                | $version                     | morepaintings-paintings-1.12.2-5.0.0.2.jar                     | None                                     |
       | UC    | morpheus                                     | 1.12-3.3.2                   | Morpheus-1.12-3.3.2.jar                                        | None                                     |
       | UC    | mrtjpcore                                    | 2.1.3.35                     | MrTJPCore-1.12.2-2.1.3.35-universal.jar                        | None                                     |
       | UC    | mystcraft                                    | 0.13.7.02                    | mystcraft-1.12.2-0.13.7.02.jar                                 | None                                     |
       | UC    | naturescompass                               | 1.5.1                        | NaturesCompass-1.12.2-1.5.1.jar                                | None                                     |
       | UC    | netherportalfix                              | 5.3.17                       | NetherPortalFix_1.12.1-5.3.17.jar                              | None                                     |
       | UC    | nmsot                                        | 1.2.2-mc1.12.2               | NoMobSpawningOnTrees-1.2.2-mc1.12.2.jar                        | None                                     |
       | UC    | recipehandler                                | 0.12                         | NoMoreRecipeConflict-0.12(1.12.2).jar                          | None                                     |
       | UC    | opframe                                      | 1.4.0                        | OnlinePicFrame_v1.4.21_mc1.12.2.jar                            | None                                     |
       | UC    | openmods                                     | 0.12.1                       | OpenModsLib-1.12.2-0.12.1.jar                                  | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | openblocks                                   | 1.8                          | OpenBlocks-1.12.2-1.8.jar                                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | UC    | orecontrol                                   | 0.4.0                        | orecontrol-1.12.0-0.4.0.jar                                    | None                                     |
       | UC    | harvestcraft                                 | 1.12.2zb                     | Pam's+HarvestCraft+1.12.2zb.jar                                | None                                     |
       | UC    | pixelmon                                     | 6.3.4                        | Pixelmon-1.12.2-6.3.4-universal.jar                            | None                                     |
       | UC    | portality                                    | 1.0-SNAPSHOT                 | portality-1.12.2-1.2.2-14.jar                                  | None                                     |
       | UC    | prettybeaches                                | 1.0.4                        | PrettyBeaches_1.12.2-1.0.4.jar                                 | None                                     |
       | UC    | forgemultipartcbe                            | 2.6.0.79                     | ~ForgeMultipart-1.12.2-2.6.0.79-universal.jar                  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | projectred-core                              | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-Base.jar                            | None                                     |
       | UC    | projectred-compat                            | 1.0                          | ProjectRed-1.12.2-4.9.1.92-compat.jar                          | None                                     |
       | UC    | projectred-integration                       | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-integration.jar                     | None                                     |
       | UC    | projectred-transmission                      | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-integration.jar                     | None                                     |
       | UC    | projectred-fabrication                       | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-fabrication.jar                     | None                                     |
       | UC    | projectred-illumination                      | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-lighting.jar                        | None                                     |
       | UC    | projectred-expansion                         | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                      | None                                     |
       | UC    | projectred-relocation                        | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                      | None                                     |
       | UC    | projectred-transportation                    | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                      | None                                     |
       | UC    | projectred-exploration                       | 4.9.1.92                     | ProjectRed-1.12.2-4.9.1.92-world.jar                           | None                                     |
       | UC    | quickleafdecay                               | 1.2.4                        | QuickLeafDecay-MC1.12.1-1.2.4.jar                              | None                                     |
       | UC    | randomthings                                 | 4.2.4                        | RandomThings-MC1.12.2-4.2.4.jar                                | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UC    | redstonearsenal                              | 2.6.1                        | RedstoneArsenal-1.12.2-2.6.1.15-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | refinedrelocation                            | 4.2.28                       | RefinedRelocation_1.12.2-4.2.28.jar                            | None                                     |
       | UC    | resourceloader                               | 1.5.3                        | ResourceLoader-MC1.12.1-1.5.3.jar                              | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | UC    | showcasemod                                  | 1.0                          | showcasemod-1.12.2-1.0.0.0.jar                                 | None                                     |
       | UC    | storagenetwork                               | 1.5.4                        | SimpleStorageNetwork-1.12.2-1.5.4.jar                          | None                                     |
       | UC    | techguns                                     | 2.0.1.1                      | techguns-1.12.2-2.0.1.1.jar                                    | None                                     |
       | UC    | thermalcultivation                           | 0.3.1                        | ThermalCultivation-1.12.2-0.3.1.8-universal.jar                | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermaldynamics                              | 2.5.3                        | ThermalDynamics-1.12.2-2.5.3.16-universal.jar                  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | thermalinnovation                            | 0.3.1                        | ThermalInnovation-1.12.2-0.3.1.8-universal.jar                 | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | UC    | tombmanygraves                               | 1.12-4.2.0                   | TombManyGraves-1.12-4.2.0.jar                                  | None                                     |
       | UC    | tombmanygraves2api                           | 1.12.2-1.0.0                 | tombmanygraves2api-1.12.2-1.0.0.jar                            | None                                     |
       | UC    | tombmanypluginstechguns                      | @VERSION@                    | tombmanypluginstechguns-1.0.0.jar                              | None                                     |
       | UC    | vanillafix                                   | 1.0.10-SNAPSHOT              | VanillaFix-1.0.10-99.jar                                       | None                                     |
       | UC    | wanionlib                                    | 1.12.2-2.1                   | WanionLib-1.12.2-2.1.jar                                       | None                                     |
       | UC    | wawla                                        | 2.5.265                      | Wawla-1.12.2-2.5.265.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UC    | wondertrade                                  | 4.5.4                        | WonderTrade-1.12.2-4.5.4-universal.jar                         | None                                     |
       | UC    | worldedit                                    | 6.1.8                        | worldedit-forge-mc1.12-6.1.8-dist.jar                          | None                                     |
       | UC    | worldeditcuife2                              | 2.1.2-mf-1.12.2-14.23.5.2768 | WorldEdit+CUI+Forge+Edition+2-2.1.2-mf-1.12.2-14.23.5.2768.jar | None                                     |
       | UC    | worleycaves                                  | 1.3.0                        | worleycaves-1.3.0.jar                                          | None                                     |
       | UC    | wrcbe                                        | 2.3.1                        | WR-CBE-1.12.2-2.3.1.30-universal.jar                           | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | UC    | yabba                                        | 1.1.2.29                     | YABBA-1.1.2.29.jar                                             | None                                     |
       | UC    | yoyos                                        | 1.12.2-1.2.2.20              | yoyos_1.12.2-1.2.2.20.jar                                      | None                                     |
       | UC    | zombie_players                               | 1.12.1-1.1.1                 | zombie_players-1.12.1-1.1.1.jar                                | None                                     |
       | UC    | zombieawareness                              | 1.12.1-1.11.14               | zombieawareness-1.12.1-1.11.14.jar                             | None                                     |
       | UC    | movingworld                                  | 1.12-6.342                   | Zzmovingworld-1.12-6.342-full.jar                              | None                                     |
       | UC    | davincisvessels                              | @DVESSELSVER@                | Zzdavincisvessels-1.12-6.340-full.jar                          | None                                     |
       | UEE   | enchiridion                                  | 3.3.4                        | ZzzEnchiridion-1.12.2-3.3.4.jar                                | None                                     |
       | U     | microblockcbe                                | 2.6.0.79                     | ~ForgeMultipart-1.12.2-2.6.0.79-universal.jar                  | None                                     |
       | U     | minecraftmultipartcbe                        | 2.6.0.79                     | ~ForgeMultipart-1.12.2-2.6.0.79-universal.jar                  | None                                     |
       | U     | lostcities                                   | 2.0.12                       | ~lostcities-1.12-2.0.12.jar                                    | None                                     |
       | U     | lostsouls                                    | 1.1.4                        | ~lostsouls-1.12-1.1.4.jar                                      | None                                     |
       | U     | malisiscore                                  | 1.12.2-6.4.0                 | ~malisiscore-1.12.2-6.4.0.jar                                  | None                                     |
       | U     | malisisdoors                                 | 1.12.2-7.3.0                 | ~malisisdoors-1.12.2-7.3.0.jar                                 | None                                     |
       | U     | reauth                                       | 3.6.0                        | reauth-3.6.0.jar                                               | None                                     |
       | U     | unidict                                      | 1.12.2-2.9.1                 | UniDict-1.12.2-2.9.1.jar                                       | None                                     |
  Loaded coremods (and transformers): RandomPatches (randompatches-1.12.2-1.11.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      LoadingPlugin (Quark-r1.5-135.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      MovingWorldCore (Zzmovingworld-1.12-6.342-full.jar)
                                        
                                      BCModPlugin (backpacks 1.12.2 - 3.5.5.jar)
                                        brad16840.core.ClassTransformer
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      Techguns Core (techguns-1.12.2-2.0.1.1.jar)
                                        techguns.core.TechgunsASMTransformer
                                      LoadingPlugin (RandomThings-MC1.12.2-4.2.4.jar)
                                        lumien.randomthings.asm.ClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.43.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.1.4.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      B3M_CorePlugin (B3M-1.12.2-02.jar)
                                        sedridor.B3M.core.B3M_Transformer
                                      MalisisCorePlugin (~malisiscore-1.12.2-6.4.0.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
                                        openmods.core.OpenModsClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.33.0 387.10.10.15.15.108' Renderer: 'NVIDIA GeForce GTX 1070 OpenGL Engine'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - craftingtweaksIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - WailaPlugin (Enabled/Not Forced)
  Suspected Mods: Enchiridion (enchiridion)
  Launched Version: 1.12.2
  LWJGL: 2.9.2
  OpenGL: NVIDIA GeForce GTX 1070 OpenGL Engine GL version 2.1 NVIDIA-10.33.0 387.10.10.15.15.108, NVIDIA Corporation
  GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
           Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel® Core™ i5-6600K CPU @ 3.50GHz

**Comment by GirafiStudios** [comment]
Thank you for reporting!
I cannot reproduce this issue. Try updating Forge?

**Comment by tacogerbil** [comment]
Is there a version you built this against?  the recommended is 2768 and I'm using 2770.. was hoping to wait until the next recommended..  but if you're building against a higher version I can try that one :)

**Comment by GirafiStudios** [comment]
Yea, the latest. It shouldn't matter tbh.
The crash is most likely cause of one of the coremods you are using.
