### ISSUE TITLE
Does not respond when importing things!

### ISSUE THREAD

**Issue by brachy84** [joshiejack/Enchiridion#119]
When i click import image ore custom button or custom background then minecraft does nothing and after like 3mins there shows up a window which says minecraft does not respond. (223 mods, custom modpack, everything else runs fine with 6gb ram allocated)

EDIT: Only happens when in Fullscreeun mode (F11)

**Comment by GirafiStudios** [comment]
Cannot reproduce. Must be your instance running out of RAM, due to the amount of mods you're running.
