### ISSUE TITLE
Crash on startup ver.3.3.4

### ISSUE THREAD

**Issue by brachy84** [joshiejack/Enchiridion#120]
Crash log:
https://pastebin.com/z6DDAV9Z
Modver.: 3.3.4
Forge ver.: 1.12.2-14.23.5.2770
Happens every time

**Comment by WolfBV** [comment]
I'm also having the same issue.

**Comment by GirafiStudios** [comment]
Please update to Minecraft Forge 14.23.5.2779 or newer.
