### ISSUE TITLE
Suggestion: Marked Template Components

### ISSUE THREAD

**Issue by Ithronyar** [joshiejack/Enchiridion#121]
Template-derived objects could have some sort of indication in the object list that they're from a template. Would make editing easier, since it would be obvious which components are from a template and which ones are unique to that page.

Example:
![templateidea](https://user-images.githubusercontent.com/26017430/51505365-f68b3c80-1d9a-11e9-9fbc-9f0ddff434fd.png)

**Comment by GirafiStudios** [comment]
Thank you for your suggestion!
Will be a part of the next version of Enchiridion
