### ISSUE TITLE
Books appear only in crearive tab

### ISSUE THREAD

**Issue by wiqg** [joshiejack/Enchiridion#123]
When i create a new book , it appears in my creative tab ''enchiridion'' . Alright...but when i create a book on survival , where does it go ? I cant make a new book on survival , only on creative gamemode.

**Comment by GirafiStudios** [comment]
The book will appear in JEI once you have restarted the game, due to how JEI determines what items/blocks to show.
You're only meant to make a new book in creative and then distribute it as part of a modpack etc.
