### ISSUE TITLE
Books that dont work as intended

### ISSUE THREAD

**Issue by drago87** [joshiejack/Enchiridion#15]
The "Chromic Lexicon" from ChromatiCraft cant be put into the Book Binder
the "World Domination with OpenBlocks" from OpenBlocks cant be opend from within the Book Binder
the "Quest Book" from Hardcore Questing Mode cant be opend from within the Book Binder

**Comment by joshiejack** [comment]
If they can't be put in. Put them in the config. If they can't be opened, they just cannot be opened in Enchiridion 1. I'll be taking a look at individual books in ench2.
