### ISSUE TITLE
Scaling Issues

### ISSUE THREAD

**Issue by Nentify** [joshiejack/Enchiridion#24]
![](http://i.nentify.me/yrNl24nF.png)

It doesn't work very well with the default Minecraft game size.

**Comment by joshiejack** [comment]
Not an issue. Fixed width is intended. Just resize the window. The default window is tiny....

**Comment by Nentify** [comment]
I've always played in the default window... I'm sure many other people do, just a bit inconvenient to have to keep fullscreening to read.
