### ISSUE TITLE
[Bug] [Crash]

### ISSUE THREAD

**Issue by SnowShock35** [joshiejack/Enchiridion#27]
MC Version: 1.7.10
Forge Version: 1277
Enchiridion Version: 2-1.7.10-2.0b

Details: adding an item into the enchiridion and trying to search causes the game to crash.

Crash Report: https://paste.ee/p/saste

**Comment by joshiejack** [comment]
The items are loaded from the creative menu. Normally there is no crash, but sometimes mods break themselves. Does creative search crash when you search these things? I'll stick in a try/catch to stop it crashing though.
