### ISSUE TITLE
Crash on clicking on the Library button

### ISSUE THREAD

**Issue by JasonMcRay** [joshiejack/Enchiridion#32]
When I click in the "wikipedia" on the Library button, my client crashes.

InfiTech 2 modpack
Enchiridion 2.0c-51
Crashlog: http://pastebin.com/hxDxYh8B

Or do I need to remove/disable the books which are not in the modpack in the library_books.json?

**Comment by joshiejack** [comment]
This crash either means: Books failed to load or the server failed to send the packet to the client to initialise the library. I can add a check to prevent it from crashing. However... If it's failing then the library will probably be empty...

**Comment by joshiejack** [comment]
Think I'll just make a dummy version of the client library, so that it will exist, rather than initialising it as null, but it won't have any books in it. I know books are syncing fine for me. Something you have must be messing with it.
