### ISSUE TITLE
Creating a link to a webpage and Embeded Video

### ISSUE THREAD

**Issue by Zodsmar** [joshiejack/Enchiridion#36]
Basically the ability to create hyperlinks or your neat Click me Buttons to go to like a wiki or google or even a youtube video. Also the ability to Embed a youtube video or something for like tutorials in maps or anything like that.

**Comment by joshiejack** [comment]
I don't think I'll do the embedding of videos in the books. It's an entirely different media that doesn't fit, however I have added option to open weblinks in the 1.8.9 version.
