### ISSUE TITLE
Spam on connecting on server

### ISSUE THREAD

**Issue by JasonMcRay** [joshiejack/Enchiridion#38]
When player connects to the server this error will appear in the server log.
http://pastebin.com/5XhjZL5G

It is not crashing, or anything bad. Just thought you might be interested in it :)

Running enchiridion 2.0d-55

**Comment by joshiejack** [comment]
This would be caused by the library adding books with null items. Did you add any books to the json file? Or alter them? Even if not, can you show me your library_books.json.

**Comment by JasonMcRay** [comment]
I havent touched the library at all. Only thing i made is one custom book.
https://github.com/JasonMcRay/InfiTech-1.7/blob/master/config/enchiridion/library_books.json

**Comment by joshiejack** [comment]
There's probably something messed up with the defaults. Is witchery:bookbiomes2 actually an item? (Someone pr'd that to me). Only wondering because all the other witchery books are ingredient...

Either way try #56
