### ISSUE TITLE
archivesBaseName should not contain a space character.

### ISSUE THREAD

**Issue by kylev** [joshiejack/Enchiridion#39]
The archivesBaseName in `build.gradle` is later used to generate the .jar files, etc. Eventually, to make it easy for others to build against this library, you'll want to publish it to Maven. According to the [Maven naming guidlines](http://maven.apache.org/guides/mini/guide-naming-conventions.html), you'll want only alpha-numeric numbers in those file names.

I have been helping people with builds and maven for a bit, and spaces and special characters cause all sorts of bothersom problems with the Java toolchain. Please rename it to "enchiridion2" or "Enchiridion2" without spaces.

You can safely use a more human readable name with spaces in the `name` field of the `mcmod.info`, and that's what will be displayed in info screens.

**Comment by joshiejack** [comment]
I have no intention to ever use maven.

**Comment by kylev** [comment]
Ok.

I hope you'll reconsider. You're already benefitting from Maven for your build environment, and it would be really great if you would use the same tools. I'm in the process of [writing a tutorial on publishing with Maven on GitHub Pages](http://kylev.github.io/nerdingcraft/github-pages-for-maven.html), and having Enchiridion available to use with a 1-line change to `build.gradle` would be awesome.
