### ISSUE TITLE
Curse Voice installing Enchiridion 2 along with Mariculture

### ISSUE THREAD

**Issue by Dwargkiller** [joshiejack/Enchiridion#41]
Hey,

Not sure if this is an error on your side or if it's related to how Curse Voice handles mod prereqs. When installing Mariculture, it automatically installs the latest version in the Enchiridion 2 marked as release: This causes it to install (at the moment) Enchiridion 2-1.7.10-2.0e.jar, while Mariculture requires Enchiridion 1.

If you want me to report it to someone else, let me know and I will. Figured you should know if you didn't already.

**Comment by joshiejack** [comment]
This isn't an issue with me. But an issue with curse not allowing me to set a version for the dependency. I guess my best bet would be to remove it as a dependency on curseforge. So it doesn't try to autodownload it.

**Comment by Dwargkiller** [comment]
I figured. Temporary measure could be to remove it as a dependency and leave a disclaimer saying that it needs manual downloading, until Curseforge allows versions for dependencies. To the suggestion forums I go! Or bugs. Hrm.. Both? Good plan. Thanks for awesome mods!

**Comment by joshiejack** [comment]
Mariculture tries to autodownload enchiridion anyways. The autoinstalling on curse, would just mean it installs both versions.

**Comment by Dwargkiller** [comment]
After installing Mariculture on Curse (where it installed Ench2) it caused a crash when trying to launch the game.

**Comment by joshiejack** [comment]
should mean* :P

**Comment by Dwargkiller** [comment]
Correction, the crash was unrelated. Installing Mariculture causes it to ask you if you want to download it, as intended. The crash was actually when I tried launching on server, which failed without asking me to download.

**Comment by joshiejack** [comment]
Ahh yeah, it's only clientside. I assume server owners would know what they're doing :P.

**Comment by Dwargkiller** [comment]
Big assumption. <3 What are the chances of a serverside automatic download if it isn't present? Would be difficult to have it ask permission, though other things download dependencies if needed (though generally not entire mods, to be fair).

**Comment by Dwargkiller** [comment]
I've sent a feedback post to curseforge about choosing specific versions of projects as dependency. I listed your case as an example of where it would be useful. One could perhaps argue that Enchiridion 1 and 2 should(might) be in seperate projects, which is how their system seems to be designed.

Then again, the ability to choose old version as dependencies wouldn't hurt either way, so a bit of a moot point.

**Comment by joshiejack** [comment]
Yeah that thought just occured to me, to split it in to a seperate project. I might do that. But not sure I really want to.
