### ISSUE TITLE
Library crash with Enchiridion 2 and Agricraft's 'Agricultural Journal'

### ISSUE THREAD

**Issue by SpiteSuicide** [joshiejack/Enchiridion#43]
I've been play testing mods together for a modpack I'm putting together and i very quickly ran into an issue. I had just added Enchiridion 2 and was having a look through of the features specifically the library. I noticed that the agricraft 'agricultural journal' was preloaded into the library so i decided to click it and got this crash http://pastebin.com/Au1XuAEw
I figured it had to do with the way the agricraft book updates when you put it in an analyzer, so to test my theory i reopened my instance grabbed the book itself in creative and opened it, no problem. Then I opened the library again and opened the agricraft book from the library, no problem just as i suspected now that i had opened the actual book. So then I grabbed an analyzer and a seed, put the book and seed in the analyzer, pulled the book out after the analyzer finished, opened agricraft book via the library and got another crash also as i suspected as the book had now updated with new seed information that was previously undiscovered (http://pastebin.com/SJVKdiGL). I'm pretty sure i can continue duplicating the crash until i run out of seeds to analyze. Hope you can help as I would really like to use your mod to help players along in my modpack because i need an easy way of explaining the changes and progression. 

-SpiteSuicide

**Comment by joshiejack** [comment]
When I added the agricraft book to the library by default, I had never actually played agricraft before. (I have extensively now). It's probably best if you just take it out of the library. With the way it works, it's not suited to being in there.

**Comment by SpiteSuicide** [comment]
I assume i can do that in the config somewhere?

**Comment by joshiejack** [comment]
Yea, just looks in the library_books.json and remove the parts about the agricraft book, try not to break the json :P

**Comment by SpiteSuicide** [comment]
Sweet thanks. Saw the Thaumnomicon in there will that have the same issue as the agricraft book?

**Comment by joshiejack** [comment]
Testing that one seems to be fine, but I don't think the research in it, gets updated.

**Comment by SpiteSuicide** [comment]
It does but probably not in the same way. I think i will remove it anyway just in case. Thanks for the swift replies.

**Comment by allout58** [comment]
Is there a way we can have a blacklist for books like this that actually break, maybe with the option to configure it for books like Thaumnomicon?
