### ISSUE TITLE
ENH: Add library support for mods using written vanilla books as user guide

### ISSUE THREAD

**Issue by ScottKillen** [joshiejack/Enchiridion#46]
[Better Chests] (https://github.com/Aroma1997/BetterChests) provides a stack with custom NBT as its user guide. See [this code](https://github.com/Aroma1997/BetterChests/blob/master/src/main/java/aroma1997/betterchests/BetterChests.java#L77) for details.

It would be great if this book was found in the library automatically and if there were a way to add others like it in `library_books.json`.

**Comment by joshiejack** [comment]
You can already add books with NBT.
Example: https://github.com/joshiejack/Enchiridion/blob/05082959cff84d4be0cd5965b7dfbe27c81acc2b/src/main/java/joshie/enchiridion/library/ModBooks.java#L111

There's the botania alfheim book. Though granted it wouldn't be easy, working out all the nbt data you would need.

Unless I misunderstood the request.

**Comment by ScottKillen** [comment]
The data is the text of the book, localized dynamically. See the source code link I posted.

**Comment by ScottKillen** [comment]
OK...I think I see how you would do it...

**Comment by ScottKillen** [comment]
I struck out. In the case of this particular book, it is a written vanilla book. The mod formats it dynamically. It uses the standard vanilla gui and the pages and physical text of the book are in the item's NBT data.

It is probably not practical to have all of that in the json file. I would think, if you wanted to support this kind of book, it would mean using reflection obtain the itemstack directly from the mod.

If you did this, the library copy would actually be superior to the mod's version, because the library would have any updates, as the library's book would be regenerated at the start of each game.

Maybe have a new book type "reflection" and the have the json provide the class and member that takes no params but returns an itemstack?
