### ISSUE TITLE
Command books

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [joshiejack/Enchiridion#47]
Feature request :dancers: 

Could do add the possibility to execute commands or on click in the book?
Could come very handy with mods like accidental circustantial events to trigger events or rewards.

**Comment by joshiejack** [comment]
I actually do have some plans with what I want to do with this. A bit more involved than what you're asking though :P

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you so much for answering joshiejack. Your mods are an essential part of my gameplay.
I will patiently wait.

**Comment by joshiejack** [comment]
This can remain open until I actually do it :P. As a reminder.
