### ISSUE TITLE
Book Color Code

### ISSUE THREAD

**Issue by Cyd007** [joshiejack/Enchiridion#48]
I was trying to change the color for the custom book icon and was unable to produce the color I wanted. I have tried using Hex RGB values and RGB Actual Values but neither produce the correct color. 

Is there another color value system or is this a bug?

**Comment by joshiejack** [comment]
I will change it to hex eventually to make it easier but right now you can use this converter.
http://www.mathsisfun.com/binary-decimal-hexadecimal-converter.html

Make sure to set it to signed 32-bit

**Comment by Cyd007** [comment]
Thank you for the response and for the info on it. I am looking forward to the additions to the editor part of Enchiridion 2.
