### ISSUE TITLE
Text display error

### ISSUE THREAD

**Issue by Joccob** [joshiejack/Enchiridion#51]
When I try to read the guide book from Advanture's Amulate mod, the characters turn into wired black rectangles. I'm using the latest ehchiridion 2.0.1. I hope there is a way to fix it.
Here is a picture: http://i1.tietuku.com/072e7046103d7130.png

**Comment by JoshuaDR** [comment]
![2015-05-27_00 55 45](https://cloud.githubusercontent.com/assets/11750955/7817969/3781b4f6-040b-11e5-8b6d-c8dfebce51b8.png)
Same. I also downloaded the adventurer's amulets mod and find the letters of its guide book having black highlights. Here is a screenshot of mine.

**Comment by GirafiStudios** [comment]
The issue is on Adventurer's Amulets side. Furthermore they have changed over to use Guide-API instead.
