### ISSUE TITLE
Lexica Botania cant open recipes

### ISSUE THREAD

**Issue by SkinHeadBaby** [joshiejack/Enchiridion#53]
when opening lexica botania from the library and on the page where you see the recipe shift clicking on items wont bring up the recipe for the selected item
if the lexicon is selected and opening the boog with the library it works just fine
this is for the latest version 2.0.2a

**Comment by joshiejack** [comment]
Just went and tested this, and it works for me. Although saying that, my dev is on Botania 180. Maybe something changed that broke it in newer versions, but either way. I don't believe anything can be done about it from my side. Not without me checking every mouse and click when the lexicon is open, and then placing a book in your held slot temporarily, which sounds like a terrible idea >.>
