### ISSUE TITLE
Tinkers Books & Book Binder

### ISSUE THREAD

**Issue by SuperSandro2000** [joshiejack/Enchiridion#55]
The Tinkers Books don't want to go in the Book Binder. I don't find the settings for that in the configs. (Older versions had that). I use the default configs and there I found the books in the library_books.json.

**Comment by shaggy1395** [comment]
The config for the Book Binder is located at \minecraft\config\books\enchiridion.cfg

You can manually add books for the book binder there.

Add these lines directly below the witchery and opencomputers books listed:

TConstruct:manualBook 0
TConstruct:manualBook 1
TConstruct:manualBook 2
TConstruct:manualBook 3
TConstruct:manualBook 4
