### ISSUE TITLE
Can't add custom enchiridion books to library

### ISSUE THREAD

**Issue by Encrypted73** [joshiejack/Enchiridion#58]
Not sure if this just isn't a thing or not but if not why isn't it?
But the issue is if I make a enchiridion book (the one from creative that says "Create a New book" Right click me to edit" (The gray book) I add the name of book "Thaumcraft Notes" then I go to Library by pressing H key and the only thing that is listed is the Thauminomicon and Tinkers and also witchery, but none of my "Custom" books show up (I made two to test this). I also did /enchiridion refresh and nothing changed, They do however show up in NEI. Am I doing something wrong or is this just not an intended feature, again why isn't it? Think it would be IMO. Anyways great mod minus this little hiccup. 
Using mod pack: Universe Of Magic (on the Curse launcher)
Thanks for any replies and sorry if this isn't the correct place for this (I'm new to Github)  :)

**Comment by shadoxxhd** [comment]
they are not placed in the library but in the wiki - try the search function

**Comment by shaggy1395** [comment]
I have created a test book using Enchiridion 2's in-game GUI.  It shows in NEI, but not in the Wiki or Library.  There also seems to be no way to create a recipe for the book so it can be acquired in any way other than cheat/creative.

**Comment by GirafiStudios** [comment]
You have to add your new custom book manually in the library_books.json.
Should be easy to figure out by looking at the default added books, the only thing that can be tircky is the stack line. It should look similiar to:"stack": "Enchiridion2:book 0 {identifier:\"book_name\"}",
