### ISSUE TITLE
Empty String Not Allowed Error Spam on Console

### ISSUE THREAD

**Issue by AuricPolaris** [joshiejack/Enchiridion#60]
Hello there,

I have noticed this empty string not allowed error on a server console whenever the server is saving. I am not sure if this is the cause of possible desyncs and latency on the server but no other error seems present via warmroast, RAM usage, opis or plugin timings. If it is not the cause that is fine, but I would like to report the error nonetheless. Pastebin of the error below.

http://pastebin.com/cjAWUCaT

Thank you and Regards,
Auric

**Comment by GirafiStudios** [comment]
What steps would I need to reproduce this?
Looks like you're using craftbukkit tho, which could be causing the issue.

**Comment by AuricPolaris** [comment]
Hi GirafiStudios,

We are currently utilizing KCauldron version 1448.152. and the two modpacks we work with containing this mod show this issue. (Agrarian Skies 2 and Beyond Reality Divergence). Please let me know if you need any further information.

**Comment by GirafiStudios** [comment]
What version of Enchiridion 2 are you using in those packs?
This issue is most likely caused by that you're running KCauldron tho.

**Comment by AuricPolaris** [comment]
Hello again,

The version in particular is 2.0.2a for both modpack servers. I understand that anything besides Forge can typically run into problems with mods (Bukkit, Cauldron, KCauldron, etc), but I, without knowing for sure that is the problem, do not want to exclude other possibilities. Is there anything else I may be able to provide to assist in understanding the problem?

**Comment by GirafiStudios** [comment]
Try if you can reproduce the problem with the latest recommended version of Minecraft Forge.
