### ISSUE TITLE
[Enchiridion 2] More Book Compatibility to the Book Binder

### ISSUE THREAD

**Issue by gabor6505** [joshiejack/Enchiridion#61]
## Description
Some books, like the Tinkers' Construct ones and the Immersive Engineer's Manual are not compatible with the ``Book Binder``, so I can't put them in. The other strange thing is that Tinkers' Construct Books are actually available from the ``Library``, but I cannot put them in the Binder. I might be missing some config files, because I saw the Library config and I don't think I can whitelist books to be able to put into the Binder, let me know.

### Some Examples:
**Tinkers' Construct**
* Materials and You: Volume 1
* Materials and You: Volume 2
* Mighty Smelting
* Diary of a Tinker
* Tinkers' Weaponry

**Immersive Engineering**
* Engineer's Manual

**Sorry if this is an intended feature or an already known issue.**

### Screenshots:
*Trying to put in the Engineer's Manual*
![2015-10-23_17 58 21](https://cloud.githubusercontent.com/assets/12859334/10699390/ceafddfa-79b6-11e5-957b-589f348bbb74.png)

### Versions:
**Enchiridion 2**: 2.0.2a

**If you need forge logs, modlist, or anything like that, tell me.**
**Thanks for the help!**

**Comment by GirafiStudios** [comment]
Similiar to #55
