### ISSUE TITLE
Crash upon opening Custom Book

### ISSUE THREAD

**Issue by SkullyGamingMC** [joshiejack/Enchiridion#63]
Hey joshiejack! I was testing out your mod and make a custom guide book for my modpack using it. It was going fine until all of a sudden it crashes everytime I open the book, giving me this crash report: http://pastebin.com/tcQnN5jE If you need to survey what the .json file of the book says I also pasted that: http://pastebin.com/5TGMpzkZ

**Comment by GirafiStudios** [comment]
Are you opening the book when held in your hand, or in the library?

**Comment by SkullyGamingMC** [comment]
Book in my hand

**Comment by GirafiStudios** [comment]
Okay. I will see if I can reproduce later.

**Comment by GirafiStudios** [comment]
From what I can see the crash happens when you enter page number 4, is that correct?

**Comment by vagaprime** [comment]
I am getting a crash when opening a custom book in hand as well. The crash happens as soon as the book is opened.

**Comment by GirafiStudios** [comment]
It would have to be caused by something you have added to the custom book. The question is just what.
Does it happen if you try to open the custom book in edit mode too?

**Comment by vagaprime** [comment]
It was crashing when I attempted to open the book outside of edit mod.

**Comment by GirafiStudios** [comment]
Are you the one who made the book? If you are, can you try to open it in edit mode?

**Comment by vagaprime** [comment]
I made the book for my pack. I am using it for the same reason that the OP is. I have just uploaded a copy of the crash log

http://pastebin.com/6xjPeA5H

**Comment by GirafiStudios** [comment]
I'm sorry I can't use the log for much, since I can't reproduce it. Is there somewhere I can download the modpack, so I can test your book?

**Comment by vagaprime** [comment]
I will see what I can do

**Comment by SkullyGamingMC** [comment]
My crash is unrelated to vagaprime's. It crashes upon opening the book on any page, both in edit mode or normal mode. The only thing I can think of is my custom logo/image on page 1

**Comment by GirafiStudios** [comment]
@SkullyGamingMC try to remove line 5 to 14 in your book .json. That's where it gets the logo from :)
