### ISSUE TITLE
[Feature Suggestion] Initial Book Crafting

### ISSUE THREAD

**Issue by BonesTheRabbit** [joshiejack/Enchiridion#66]
So, just throwing this out there as a possible suggestion, but it would be interesting if the library only populated once books have been initially crafted. For example, once you make a witchery book, it'll be added to the library, and you'll never have to make it again. But it still necessitates that initial crafting.

This option would be really intuitive for mods like thaumcraft, for example.

**Comment by thephoenixlodge** [comment]
You can already set this up in the configs, and it is exactly how I set it up in Regrowth.
