### ISSUE TITLE
Books not being added to Library on pickup

### ISSUE THREAD

**Issue by Mordenkainen** [joshiejack/Enchiridion#71]
Using v2.0.1 via the Regrowth modpack and books are not being added to the library on pickup though they are configured to do so.

Crafting a book does properly add it to the library.

This is happening to all players on the server.

It appears that this is working properly in single player.

In Regrowth this is somewhat of an issue because several books are given as rewards so the player does not have to craft them.

**Comment by joshiejack** [comment]
1.7.10 version is no longer supported. Sorry.
