### ISSUE TITLE
Can´t edit .json of a custom Book

### ISSUE THREAD

**Issue by LukeSkywaIker** [joshiejack/Enchiridion#72]
Maybe i´m totally stupid, but im not able to edit books via .json file.

i read the ingame wiki for creating a new book. 
the problem is when i create a new book via shift-rightclick or by creating a new json i not able to re-edit it. for example:

created book (shift-rightclick) named it ABC
put in a crafting grid, then close editing gui.
went to config/enchiridion/books, opened the ABC.json, edited the item in crafting grid.
restart minecraft, opened book, change doesnt apply.

with another custom book i changed the name in json after ingame editing.
after opening it ingame the json were reseted to an empty book.

any ideas?

mc 1.7.10
forge 10.13.4.1558
ench 2-1.7.10-2.0.2a

@joshiejack

**Comment by LukeSkywaIker** [comment]
no answer. just closed?

**Comment by GirafiStudios** [comment]
1.7.10 is not beeing supported anymore. I just tested that exact feature myself on the same version. Works just fine for me tho.

**Comment by LukeSkywaIker** [comment]
ah, ok. thx for the answer!
