### ISSUE TITLE
Feature request: run command as click action

### ISSUE THREAD

**Issue by dualcoding** [joshiejack/Enchiridion#73]
Vanilla books if spawned with the right NBT data can be made to run commands by clicking text. It would be nice if Enchiridion had a similar feature.

I believe this would be very convenient for ops and creative players alike, as well as making it easier to create truly magical books that can interact with the world in custom maps.

See for instance https://raw.githubusercontent.com/TheWebmage/commands-json/master/Magic%20Book

**Comment by joshiejack** [comment]
Shouldn't be too hard to do

**Comment by dualcoding** [comment]
Quick work! Thanks.
