### ISSUE TITLE
Fix JEI Safestack or w/e

### ISSUE THREAD

**Issue by GirafiStudios** [joshiejack/Enchiridion#77]
:3

**Comment by joshiejack** [comment]
Reminder:
<joshiejack> https://github.com/joshiejack/Enchiridion/blob/b909a0752639663aaa4cada5fd58ea261b2371a0/src/main/java/joshie/enchiridion/jei/LibraryRecipeWrapper.java#L23
<joshiejack> https://github.com/joshiejack/Enchiridion/blob/b909a0752639663aaa4cada5fd58ea261b2371a0/src/main/java/joshie/enchiridion/gui/library/LibraryRecipe.java#L15
