### ISSUE TITLE
Added TiCo book to configs and received crash.

### ISSUE THREAD

**Issue by GodNero** [joshiejack/Enchiridion#78]
So I added TiCo's "Materials and You" to the end of ssp.cfg lines 153 - 158 found at this [pastebin](http://pastebin.com/6y0prgGB).

and [this](http://pastebin.com/f7QBR57u) is the crash I got.

If I entered the book incorrectly let me know.

**Comment by joshiejack** [comment]
Two things. Incorrectly formatted JSON.
http://i.imgur.com/JTbiQTg.png

 You forgot a comma. And two you need to make the handlerType rightclick.

**Comment by GodNero** [comment]
Yeah, I see where I missed them both. Fixed it, all good now thanks for helping me with my horrible syntax :p
