### ISSUE TITLE
Attempting to add and Image to a custom book causes crash

### ISSUE THREAD

**Issue by OCDiary** [joshiejack/Enchiridion#80]
Hi,
When I am trying to add a custom image to a custom book in the version 2.0.2a it cause java to crash and force close.

I am playing on 1.7.10 and it does not seem to create a crash-log for the event.

**Comment by joshiejack** [comment]
Without a crash report and not being able to recreate the issue, can't do much. Maybe it's to do with the image or it's name. Either way the 1.7.10 version is done so am closing this.
