### ISSUE TITLE
books needed to add

### ISSUE THREAD

**Issue by bird191** [joshiejack/Enchiridion#81]
there are 2 mods you have missed adding books from one is ars magica 2 which has compatability to work inside the book binder but has no book in the library. The other mod is immersive engineering which does not work with book binder and is not in the library.

**Comment by joshiejack** [comment]
There are configs for a reason. Also by the sounds of it you're on 1.7.10, which is no longer developed anyway. Come back to me when mods are updated for 1.9.4/1.10.2.

**Comment by bird191** [comment]
A lot of people still use 1.7.10 so why not add those 2 mods to the library
just to be helpful towhat a good majority of people use like rrm is still
1.7.10 and a lot of people use that

**Comment by joshiejack** [comment]
Because I don't have the bloody time. I have lots of mods to work on. I am not wasting my time on 1.7.10. I don't care what other people are doing.

**Comment by bird191** [comment]
How many mods do you work on? Also you should care about the community as a
whole not only care about the ones using current minecraft and you can
blame other modders who don't update their mods to 1.9 to the reason so
many people who use 1.7.10.

**Comment by joshiejack** [comment]
Four currently. And you just solved your problem, go and complain to those other modders not me.
