### ISSUE TITLE
/help breaking

### ISSUE THREAD

**Issue by C0rn3j** [joshiejack/Enchiridion#87]
Forge 2092

http://pastebin.com/y3hRUmby : Line 1802

**Comment by C0rn3j** [comment]
Actually just tried to load this without HelpFixer and /help still works. 

EDIT: Actually... the issue is there but is server side!

Why would you just randomly close the issue though?

This is how LootBags fixed the same issue on their side.
https://github.com/Malorolam/LootBags/commit/2647147688ea02e3de88c87e5e927a5e2dbfd6c8

It breaks stuff.
http://i.imgur.com/A7p7pfq.png

**Comment by C0rn3j** [comment]
Actually... the issue is server side!

**Comment by C0rn3j** [comment]
Why would you just randomly close the issue though?

**Comment by C0rn3j** [comment]
This is how LootBags fixed the same issue on their side.
https://github.com/Malorolam/LootBags/commit/2647147688ea02e3de88c87e5e927a5e2dbfd6c8

It breaks stuff.
http://i.imgur.com/A7p7pfq.png

**Comment by joshiejack** [comment]
Don't know why I closed it, think maybe because it was another mod whining. Plus I was like asleep and the email notification annoyed me xD. No need to comment 500 times though.
