### ISSUE TITLE
Crash with a GuideAPI book

### ISSUE THREAD

**Issue by TonRZN** [joshiejack/Enchiridion#88]
You can change normally to the book, but when you close it crashes the game

**Comment by joshiejack** [comment]
Umm. Are you even going to give me a crash report. Or you want me to go on a wild goose chase? It worked fine for me with the blood magic book from guide api.

**Comment by TonRZN** [comment]
Sorry, I forgot. Here are the pastebin link for the crash part of the log http://pastebin.com/cpBcdidR
And here the full log http://pastebin.com/L1KniQ2Z
Actually there's no crash log, the game just froze and get stuck
And the issue happen with the blood magic book

**Comment by joshiejack** [comment]
Out of interest what did you list the book as in your json.

**Comment by TonRZN** [comment]
But i'm using the default configs, i actually deleted the enchiridion folder just to see if the problem was on the configs

**Comment by joshiejack** [comment]
That is why i asked... How am I meant to know you did that?

**Comment by TonRZN** [comment]
I don't speak English normally, sorry, so I didn't understood your question
But yes, I'm using the defaults
