### ISSUE TITLE
[1.10.2] Crash with latest JEI version

### ISSUE THREAD

**Issue by SeriousCreeper** [joshiejack/Enchiridion#89]
crashlog: http://pastebin.com/UcdmeaKA 

crashes when creating a new world. 
Forge 2094, latest enchiridion and latest jei versions, nothing else in the pack!

**Comment by GirafiStudios** [comment]
Thank you for reporting!
JEI is doing a big refractor which included removing a class Enchiridion were extending, will be fixed in next version of Enchiridion. For now please use JEI version 3.10.0.268.
