### ISSUE TITLE
Can't get my book to load

### ISSUE THREAD

**Issue by TheUnChosenOne** [joshiejack/Enchiridion#90]
i am using enchiridion v3 but every time i make a book and it will not load on the 3rd time i run the game.

**Comment by joshiejack** [comment]
provide proof

**Comment by TheUnChosenOne** [comment]
https://imgur.com/a/2pc57
is the proof good for you

**Comment by joshiejack** [comment]
I would ask for the json but it's been so long since I've worked on Enchiridion I've forgot what it's supposed to look like xD.

**Comment by TheUnChosenOne** [comment]
lol

**Comment by TheUnChosenOne** [comment]
if i just make a book it will be ok but when i start editing it and adding more than one page it will load the first time i save and quit the game the second time is iffy but the third time i get on minecraft it will not load

**Comment by TheUnChosenOne** [comment]
https://dl.dropboxusercontent.com/u/92193552/ThePack.json

**Comment by GirafiStudios** [comment]
Thanks for the report @jackmaster9000 !
This seem to be an issue with Enchiridion support in Progression. Maybe you have removed Progression from your pack?
Closing this, since it is not caused by Enchiridion. I suggest you go report it to Progression at https://github.com/joshiejack/Progression :)
