### ISSUE TITLE
Server Side Console Spam

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [joshiejack/Enchiridion#91]
https://gist.github.com/P3rf3ctXZer0/7aa0b732b53dd181f3cd0b7ae8d451a8

**Comment by GirafiStudios** [comment]
What version of Enchiridion are you using - and what are you doing to make this happen? :)

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/PenguinSquad/Enchiridion/commit/bd737f3825131f17b0ac22c5b6eb8b9ccb7fa3e2
