### ISSUE TITLE
Error when someone joins server

### ISSUE THREAD

**Issue by CourtArtanis** [joshiejack/Enchiridion#92]
The below hits the console everytime any player logs into the server.

Any ideas what could be causing it?
Thanks

version: Enchiridion 2-1.7.10-2.0.2a

**Comment by GirafiStudios** [comment]
Thanks for the report!
What version of Enchiridion are you using ? :)

**Comment by CourtArtanis** [comment]
I just updated the post as you replied :+1:

**Comment by GirafiStudios** [comment]
@CourtArtanis yeah sorry, we haven't supported 1.7.10 in about 2 years.
