### ISSUE TITLE
Incorrect display of formatting characters.

### ISSUE THREAD

**Issue by gdude2002** [joshiejack/Enchiridion#93]
I posted a comment on Curse, but then realised you guys had an issue tracker here.

---
MC: 1.10.2 (Multiplayer)
Forge: 12.18.3.2185
Enchiridion: 1.10.2 - 3.1.14

It seems that formatting (using the section sign) isn't saving correctly on the server. On restarting my client and rejoining the server, all section signs are prefixed with a Unicode accented A. Any ideas on this one?

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/December/java_2016-12-11_00-54-14.png)

Even if I manually go in and remove these characters, they come back if I restart my client and rejoin.

**Comment by GirafiStudios** [comment]
How are you setting the text colors ? :)

**Comment by gdude2002** [comment]
By pasting in the Minecraft formatting codes, eg `§4` for dark red.

Also, I just noticed this didn't actually sync to the server - it's stored
locally, which explains why it gets reloaded when I restart the client.

**Comment by gdude2002** [comment]
By pasting in the Minecraft formatting codes, eg `§4` for dark red.

Also, I just noticed this didn't actually sync to the server - it's stored
locally, which explains why it gets reloaded when I restart the client.

**Comment by GirafiStudios** [comment]
Setting the colors with the Minecraft color codes are not the way you are meant to color your text in Enchiridion.
Instead you are meant to use something like: " [color=red]Rules & guidelines "

**Comment by gdude2002** [comment]
Is this kind of thing documented anywhere? How do I do stuff like bold?

**Comment by GirafiStudios** [comment]
[b]Text[/b] to do bold text etc.

**Comment by gdude2002** [comment]
so, `b`old, `i`talic, `u`nderline, `r`eset and.. `k`?

**Comment by joshiejack** [comment]
https://github.com/PenguinSquad/Enchiridion/blob/1.10.2/src/main/java/joshie/enchiridion/util/PenguinFont.java#L79


Please don't ask why I did this, stupid me thought it would be easier.

**Comment by gdude2002** [comment]
It's not an awful way of doing it. I still think you should be able to support people adding the signs in manually, though - maybe it's a file encoding issue?

**Comment by gdude2002** [comment]
@joshiejack @GirafiStudios This looks to be a wider issue, actually.

![](https://dl.dropboxusercontent.com/u/1547120/ShareX/2016/December/java_2016-12-12_18-46-58.png)

You might want to check the file encoding of these JSON files, it looks like they can't really handle Unicode.
