### ISSUE TITLE
crash when adding recipe for floating flowers from botania

### ISSUE THREAD

**Issue by SDUBZ** [joshiejack/Enchiridion#94]
[crash-2016-12-18_12.00.51-client.txt](https://github.com/PenguinSquad/Enchiridion/files/659185/crash-2016-12-18_12.00.51-client.txt)
enchiridon: Enchiridion-1.10.2-3.1.14
forge: 1.10.2-2185
botania: Botania r1.9-339

**Comment by GirafiStudios** [comment]
Thanks for reporting!
I'm afraid I cannot reproduce your issue including all the mods mentioned in the stacktrace (Botania, Chisels & Bits and CodeChicken Lib). Some other mod must be messing with the rendering, not sure which though.
If you could try to track down what mod is causing it, that would be great!
