### ISSUE TITLE
Request - 1.10.2 - Support for village box books and pokecube pokedex.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [joshiejack/Enchiridion#95]
![tdgtd](https://cloud.githubusercontent.com/assets/10351221/21596460/122aa13a-d101-11e6-9e1d-ad0c7eb8606e.PNG)
Title says it all.
![wont stay](https://cloud.githubusercontent.com/assets/10351221/21596432/c5bbc98c-d100-11e6-8a97-2abaf2eba934.PNG)
The village box 

In regards to the pokedex I don't expect to be able to open it because it has its own GUI and a bunch of other functions. I just want to store it there.

**Comment by joshiejack** [comment]
You can add books to the config files yourself. Even if @GirafiStudios does this by default you'd still need to update/delete your existing config for it to work.

**Comment by GirafiStudios** [comment]
Yeah as Joshie said you can add the book yourself in config/enchiridion/ssp.json.
I just did a release for 1.10.2 the other day adding support for more books, not planning to do any 1.10.2 releases anytime soon, unless it is a major bug.
