### ISSUE TITLE
On 1.11.2, I can't edit my newly created book

### ISSUE THREAD

**Issue by trainzkid** [joshiejack/Enchiridion#97]
After successfully finding the new book I created (it didn't automatically appear in my inventory, but it was searchable), I opened it and there's no way for me to edit it. It's just a blank book with page turn buttons. 

I tried in both creative and survival. 

The only mods currently active are JEI, Guide-API, and enchiridion version 3.1.17.

[Here's](http://imgur.com/a/W5E9a) some pics for proof.
No crashes, just don't know how to edit this new book I created.

The json was created with code and everything:
`{
  "uniqueName": "How_to_Not_Die_in_the_Nether",
  "saveName": "How_to_Not_Die_in_the_Nether",
  "displayName": "How to Not Die in the Nether",
  "colorHex": "FFFFFFFF",
  "language": "en_us",
  "hasCustomIcon": true,
  "showBackground": true,
  "legacyTexture": false,
  "backgroundResource": "enchiridion:textures/books/rustic2.png",
  "BACKGROUND_START_X": -10,
  "BACKGROUND_START_Y": -10,
  "BACKGROUND_END_X": 440,
  "BACKGROUND_END_Y": 240,
  "defaultPage": 0,
  "isLocked": false,
  "forgetPageOnClose": false,
  "book": [
    {
      "features": [
        {
          "xPos": 21,
          "yPos": 200,
          "width": 18.0,
          "height": 10.0,
          "feature": {
            "class": "joshie.enchiridion.gui.book.features.FeatureButton",
            "properties": {
              "action": {
                "class": "joshie.enchiridion.gui.book.buttons.actions.ActionPreviousPage",
                "properties": {}
              },
              "size": 1.0,
              "leftClick": true,
              "rightClick": true,
              "otherClick": false,
              "tooltip": "",
              "hoverText": "",
              "hoverXOffset": 0,
              "hoverYOffset": 0,
              "unhoveredText": "",
              "unhoveredXOffset": 0,
              "unhoveredYOffset": 0,
              "hoveredResource": "enchiridion:textures/books/arrow_left_on.png",
              "unhoveredResource": "enchiridion:textures/books/arrow_left_off.png"
            }
          },
          "isLocked": true,
          "isHidden": false,
          "layerIndex": 0
        },
        {
          "xPos": 387,
          "yPos": 200,
          "width": 18.0,
          "height": 10.0,
          "feature": {
            "class": "joshie.enchiridion.gui.book.features.FeatureButton",
            "properties": {
              "action": {
                "class": "joshie.enchiridion.gui.book.buttons.actions.ActionNextPage",
                "properties": {}
              },
              "size": 1.0,
              "leftClick": true,
              "rightClick": true,
              "otherClick": false,
              "tooltip": "",
              "hoverText": "",
              "hoverXOffset": 0,
              "hoverYOffset": 0,
              "unhoveredText": "",
              "unhoveredXOffset": 0,
              "unhoveredYOffset": 0,
              "hoveredResource": "enchiridion:textures/books/arrow_right_on.png",
              "unhoveredResource": "enchiridion:textures/books/arrow_right_off.png"
            }
          },
          "isLocked": true,
          "isHidden": false,
          "layerIndex": 1
        }
      ],
      "pageNumber": 0,
      "isScrollable": false
    }
  ],
  "defaultIDs": [
    "enchiridion_default_buttons"
  ]
}`

**Comment by joshiejack** [comment]
Is editing enabled in config and are you shift clicking

**Comment by trainzkid** [comment]
Editing yes, shift clicking no, I'll test in a sec, thank you

**Comment by trainzkid** [comment]
Shift Clicking worked, thank you
