### ISSUE TITLE
[1.10.2] Cannot get the Modifiable Armor Mod's book to work

### ISSUE THREAD

**Issue by brisingraerowing** [joshiejack/Enchiridion#98]
I use the Modifiable Armor mod, and the item ID of the book has spaces in it (which I wasn't aware of being valid), and even if I put it into the Enchridon library JSON file, it doesn't work.

The ID (copied direct from MC): "modifiable_armor:Modifiable Armor Book"

Is there a work around, or should I poke the author of Modifiable Armor about this?

**Comment by joshiejack** [comment]
replace the spaces with %20 so
modifiable_armor:Modifiable%20Armor%20Book

And you're right, item names shouldn't have spaces but ehh. They should be using underscores and all lowercase...

**Comment by brisingraerowing** [comment]
Ah, OK. Thanks for the tip!
