### ISSUE TITLE
1.11.2 BOOKS error

### ISSUE THREAD

**Issue by MysticalDwat** [joshiejack/Enchiridion#99]
I have been trying to use the mod but there is an error in which the crash report says no field name error:BOOKS. here is the crash report.
[crash-2017-05-30_11.19.47-server.txt](https://github.com/PenguinSquad/Enchiridion/files/1038802/crash-2017-05-30_11.19.47-server.txt)

**Comment by sandalle** [comment]
Same crash here on Minecraft 1.11.2 and Forge 1.11.2-13.20.0.2315 when creating a _new_ SSP (single player) world from the client. Existing worlds or creating a world on a headless server (Linux) generate fine.

[crash-2017-06-20_19.58.50-server.txt](https://github.com/PenguinSquad/Enchiridion/files/1090230/crash-2017-06-20_19.58.50-server.txt)

**Comment by GirafiStudios** [comment]
Fixed in https://github.com/PenguinSquad/Enchiridion/commit/f040adb99909bd5c9ef84de5be6f2ac5c21dc22f
New release will be out on CurseForge later today hopefully.
